
debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.guide.board: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: debug
    org.springframework.transaction.interceptor: debug

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: w0nnie
    password: 1111
#    url: jdbc:h2:mem:testdb
#    username: sa
#    driver-class-name: org.h2.Driver
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
#  h2.console.enabled: true
  sql.init.mode: always
  data:
    rest:
      base-path: /api
      detection-strategy: annotated